name: Python application (multi-project)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: "${{ matrix.project.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project:
              name: Degrees
              path: degrees
              entry: "python degrees.py"      # add args if your script needs them
          - project:
              name: Knights
              path: knights
              entry: "python puzzle.py"
          - project:
              name: Tic Tac Toe
              path: tictactoe
              entry: "python runner.py"
          - project:
              name: Minesweeper
              path: minesweeper
              entry: "python runner.py"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # NOTE: do NOT set cache-dependency-path to a .py file.
          # We'll keep caching simple; it will no-op if there's no requirements file.
          cache: pip

      - name: Show project tree (debug)
        run: |
          echo "Repo root:"
          ls -la
          echo "Project dir:"
          ls -la "${{ matrix.project.path }}"

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Install project dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            echo "Installing dependencies from requirements.txt"
            pip install -r requirements.txt
          else
            echo "No requirements.txt found in $(pwd); skipping."
          fi
        working-directory: ${{ matrix.project.path }}

      - name: Lint with flake8
        run: |
          # Fail on syntax errors/undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Treat other findings as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ${{ matrix.project.path }}

      - name: Run tests (if present)
        run: |
          if [ -d tests ] || compgen -G "*test*.py" > /dev/null; then
            pytest -q
          else
            echo "No tests detected, skipping pytest."
          fi
        working-directory: ${{ matrix.project.path }}

      - name: Run project
        run: ${{ matrix.project.entry }}
        working-directory: ${{ matrix.project.path }}
